apiVersion: v1
kind: Service
metadata:
        name: spk-service
spec:
        type: NodePort
        selector:
                app: spk
        ports:
                - protocol: TCP
                  port: 80
                  nodePort: 31072
