# Generated by Django 3.1.3 on 2020-11-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_infinitive', models.CharField(max_length=50)),
                ('glosses', models.JSONField()),
                ('verbtype', models.CharField(max_length=25)),
                ('verbtype_i', models.SmallIntegerField()),
            ],
        ),
    ]
